import { customType } from 'drizzle-orm/pg-core'
import { Coordinates } from '@whosonsite/shared'

/**
 * Parses Extended Well-Known Binary (EWKB) data returned by PostGIS/node-postgres.
 *
 * Decodes 64-bit IEEE 754 floating-point coordinates (longitude and latitude)
 * from EWKB byte buffers or hex-encoded strings generated by PostGIS geography columns.
 *
 * @param value Hex-encoded string or raw Buffer containing PostGIS EWKB binary data
 * @returns Decoded Coordinates object with lat and lng, or null if parsing fails
 */
function parseEwkb(value: string | Buffer): Coordinates | null {
  try {
    const buf = typeof value === 'string' ? Buffer.from(value, 'hex') : value
    if (!buf || buf.length < 21) return null

    // Determine endianness byte (1 = Little Endian, 0 = Big Endian)
    const littleEndian = buf[0] === 1
    const type = littleEndian ? buf.readUInt32LE(1) : buf.readUInt32BE(1)

    // Account for SRID presence in geometry header (SRID flag 0x20000000 or type 1 with SRID)
    let offset = 5
    if ((type & 0x20000000) !== 0 || ((type & 0xffff) === 1 && buf.length >= 25)) {
      offset = 9
    }

    // Read longitude (X) and latitude (Y) as 64-bit doubles
    const lng = littleEndian ? buf.readDoubleLE(offset) : buf.readDoubleBE(offset)
    const lat = littleEndian ? buf.readDoubleLE(offset + 8) : buf.readDoubleBE(offset + 8)

    // Validate geographic coordinate boundaries
    if (!isNaN(lat) && !isNaN(lng) && lat >= -90 && lat <= 90 && lng >= -180 && lng <= 180) {
      return { lat, lng }
    }
  } catch {
    // Return null fallback if binary buffer decoding fails
  }
  return null
}

/**
 * Custom Drizzle ORM type for PostGIS `geography` columns.
 *
 * Handles bi-directional mapping between TypeScript `Coordinates` objects ({ lat, lng })
 * and PostGIS SRID 4326 geography points stored in PostgreSQL.
 */
export const postgisGeometry = customType<{
  data: Coordinates
  driverData: string
}>({
  /** Returns database column type name */
  dataType() {
    return 'geography'
  },

  /** Converts TypeScript Coordinates object to PostGIS SQL function call */
  toDriver(value: Coordinates): string {
    return `ST_SetSRID(ST_MakePoint(${value.lng}, ${value.lat}), 4326)`
  },

  /**
   * Converts PostGIS geography output (EWKB hex string, Buffer, GeoJSON object, or WKT string)
   * into a standardized TypeScript Coordinates object ({ lat, lng }).
   *
   * @param value Raw driver column value returned by node-postgres
   * @returns Validated Coordinates object or default zero coordinate fallback
   */
  fromDriver(value: unknown): Coordinates {
    if (!value) return { lat: 0, lng: 0 }

    // Direct binary Buffer parsing for raw EWKB byte streams
    if (Buffer.isBuffer(value)) {
      const parsed = parseEwkb(value)
      if (parsed) return parsed
    }

    // Object parsing for pre-parsed GeoJSON or { x, y } / { lat, lng } driver objects
    if (typeof value === 'object' && value !== null) {
      const obj = value as Record<string, unknown>
      if (typeof obj.lat === 'number' && typeof obj.lng === 'number') {
        return { lat: obj.lat, lng: obj.lng }
      }
      if (typeof obj.x === 'number' && typeof obj.y === 'number') {
        return { lat: obj.y, lng: obj.x }
      }
      if (Array.isArray(obj.coordinates) && obj.coordinates.length >= 2) {
        return {
          lng: Number(obj.coordinates[0]),
          lat: Number(obj.coordinates[1])
        }
      }
    }

    // String parsing for WKT POINT strings, EWKB hex strings, or stringified GeoJSON
    if (typeof value === 'string') {
      // WKT POINT(lng lat) format
      const match = value.match(/POINT\s*\(\s*([-\d.]+)\s+([-\d.]+)\s*\)/i)
      if (match) {
        return { lng: parseFloat(match[1]), lat: parseFloat(match[2]) }
      }

      // EWKB Hex string format
      const parsedEwkb = parseEwkb(value)
      if (parsedEwkb) return parsedEwkb

      // Stringified GeoJSON object fallback
      try {
        const parsed = JSON.parse(value)
        if (parsed && typeof parsed === 'object') {
          const pObj = parsed as Record<string, unknown>
          if (typeof pObj.lat === 'number' && typeof pObj.lng === 'number') {
            return { lat: pObj.lat, lng: pObj.lng }
          }
          if (typeof pObj.x === 'number' && typeof pObj.y === 'number') {
            return { lat: pObj.y, lng: pObj.x }
          }
          if (Array.isArray(pObj.coordinates) && pObj.coordinates.length >= 2) {
            return { lng: Number(pObj.coordinates[0]), lat: Number(pObj.coordinates[1]) }
          }
        }
      } catch {
        // Fall through to default fallback
      }
    }

    return { lat: 0, lng: 0 }
  }
})
